name: GitHub-Profile-3D-Contrib-and-Summary-Cards

on:
  push:
    branches:
      - master  
  schedule:
    - cron: "0 18 * * *"  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib-and-summary-cards
    steps:
      - uses: actions/checkout@v3

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push 3D Profile
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add profile-3d-contrib/ 
          git diff-index --quiet HEAD || git commit -m "Generated 3D profile contribution graph"
          git push

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push Summary Cards
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add profile-summary-card-output/ 
          git diff-index --quiet HEAD || git commit -m "Generated GitHub profile summary cards"
          git push